from __future__ import annotations

from typing import Protocol, runtime_checkable

from sim.config import SimulationConfig


@runtime_checkable
class ControlChannel(Protocol):
    """Generic communication channel between trainer/controller and simulator."""

    def get_command(self) -> int:
        ...

    def set_command(self, command: int) -> None:
        ...

    def get_position(self) -> int:
        ...

    def close(self) -> None:
        ...


@runtime_checkable
class ExperienceStore(Protocol):
    """Generic storage interface for experiences generated by the simulator."""

    def has_completed_experience(self, start_position: int) -> bool:
        ...

    def close(self) -> None:
        ...


@runtime_checkable
class EventDrivenSystem(Protocol):
    """
    Minimal adapter for any event-driven system.

    A SimPy model, a custom discrete-event simulator, or an external simulator
    should implement this protocol. The RL package should only depend on this
    protocol, not on a domain package.
    """

    config: SimulationConfig
    control: ControlChannel
    experiences: ExperienceStore

    def now(self) -> float:
        ...

    def run_until(self, target_time: float) -> None:
        ...

    def enable_policy_initialization(self) -> None:
        ...

    def request_policy_sync(self) -> None:
        ...

    def close(self) -> None:
        ...
